name: medifinder
description: A new Flutter project.
version: 1.0.0+1
environment:
  sdk: ">=2.12.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cached_network_image: ^3.3.0
  flutter_svg: ^2.0.9
  get: ^4.6.6
  shared_preferences: ^2.2.2
  connectivity_plus: ^6.0.3
  intl: ^0.18.0
  firebase_core: ^2.29.0
  firebase_auth: ^4.19.1
  google_sign_in: ^6.2.1
  image_picker: ^1.0.8
  firebase_storage: ^11.7.1
  cloud_firestore: ^4.17.0
  awesome_dialog: ^3.2.0
  shimmer: ^3.0.0
  image_cropper: ^6.0.0
  flutter_image_compress: ^2.3.0
  path_provider: ^2.1.3
  flutter_screenutil: ^5.9.3
  dio: ^5.5.0+1
  lottie: ^3.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.13.1"

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.png"
flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/PoppinsSemiBold.ttf
          weight: 600
        - asset: assets/fonts/PoppinsRegular.ttf
          weight: 400
